<?php

/* custom routes generated by CRUD */


Route::group(array('prefix' => 'admin/554/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.554.'), function () {

Route::get('atletas', ['as'=> 'atletas.index', 'uses' => '554\AtletasController@index']);
Route::post('atletas', ['as'=> 'atletas.store', 'uses' => '554\AtletasController@store']);
Route::get('atletas/create', ['as'=> 'atletas.create', 'uses' => '554\AtletasController@create']);
Route::put('atletas/{atletas}', ['as'=> 'atletas.update', 'uses' => '554\AtletasController@update']);
Route::patch('atletas/{atletas}', ['as'=> 'atletas.update', 'uses' => '554\AtletasController@update']);
Route::get('atletas/{id}/delete', array('as' => 'atletas.delete', 'uses' => '554\AtletasController@getDelete'));
Route::get('atletas/{id}/confirm-delete', array('as' => 'atletas.confirm-delete', 'uses' => '554\AtletasController@getModalDelete'));
Route::get('atletas/{atletas}', ['as'=> 'atletas.show', 'uses' => '554\AtletasController@show']);
Route::get('atletas/{atletas}/edit', ['as'=> 'atletas.edit', 'uses' => '554\AtletasController@edit']);

});


Route::group(array('prefix' => 'admin/554/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.554.'), function () {

Route::get('atletas', ['as'=> 'atletas.index', 'uses' => '554\AtletasController@index']);
Route::post('atletas', ['as'=> 'atletas.store', 'uses' => '554\AtletasController@store']);
Route::get('atletas/create', ['as'=> 'atletas.create', 'uses' => '554\AtletasController@create']);
Route::put('atletas/{atletas}', ['as'=> 'atletas.update', 'uses' => '554\AtletasController@update']);
Route::patch('atletas/{atletas}', ['as'=> 'atletas.update', 'uses' => '554\AtletasController@update']);
Route::get('atletas/{id}/delete', array('as' => 'atletas.delete', 'uses' => '554\AtletasController@getDelete'));
Route::get('atletas/{id}/confirm-delete', array('as' => 'atletas.confirm-delete', 'uses' => '554\AtletasController@getModalDelete'));
Route::get('atletas/{atletas}', ['as'=> 'atletas.show', 'uses' => '554\AtletasController@show']);
Route::get('atletas/{atletas}/edit', ['as'=> 'atletas.edit', 'uses' => '554\AtletasController@edit']);

});


Route::group(array('prefix' => 'admin/554/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.554.'), function () {

Route::get('atletas', ['as'=> 'atletas.index', 'uses' => '554\AtletasController@index']);
Route::post('atletas', ['as'=> 'atletas.store', 'uses' => '554\AtletasController@store']);
Route::get('atletas/create', ['as'=> 'atletas.create', 'uses' => '554\AtletasController@create']);
Route::put('atletas/{atletas}', ['as'=> 'atletas.update', 'uses' => '554\AtletasController@update']);
Route::patch('atletas/{atletas}', ['as'=> 'atletas.update', 'uses' => '554\AtletasController@update']);
Route::get('atletas/{id}/delete', array('as' => 'atletas.delete', 'uses' => '554\AtletasController@getDelete'));
Route::get('atletas/{id}/confirm-delete', array('as' => 'atletas.confirm-delete', 'uses' => '554\AtletasController@getModalDelete'));
Route::get('atletas/{atletas}', ['as'=> 'atletas.show', 'uses' => '554\AtletasController@show']);
Route::get('atletas/{atletas}/edit', ['as'=> 'atletas.edit', 'uses' => '554\AtletasController@edit']);

});


Route::group(array('prefix' => 'admin/554/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.554.'), function () {

Route::get('atletas', ['as'=> 'atletas.index', 'uses' => '554\AtletasController@index']);
Route::post('atletas', ['as'=> 'atletas.store', 'uses' => '554\AtletasController@store']);
Route::get('atletas/create', ['as'=> 'atletas.create', 'uses' => '554\AtletasController@create']);
Route::put('atletas/{atletas}', ['as'=> 'atletas.update', 'uses' => '554\AtletasController@update']);
Route::patch('atletas/{atletas}', ['as'=> 'atletas.update', 'uses' => '554\AtletasController@update']);
Route::get('atletas/{id}/delete', array('as' => 'atletas.delete', 'uses' => '554\AtletasController@getDelete'));
Route::get('atletas/{id}/confirm-delete', array('as' => 'atletas.confirm-delete', 'uses' => '554\AtletasController@getModalDelete'));
Route::get('atletas/{atletas}', ['as'=> 'atletas.show', 'uses' => '554\AtletasController@show']);
Route::get('atletas/{atletas}/edit', ['as'=> 'atletas.edit', 'uses' => '554\AtletasController@edit']);

});


Route::group(array('prefix' => 'admin/554/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.554.'), function () {

Route::get('atletas', ['as'=> 'atletas.index', 'uses' => '554\AtletasController@index']);
Route::post('atletas', ['as'=> 'atletas.store', 'uses' => '554\AtletasController@store']);
Route::get('atletas/create', ['as'=> 'atletas.create', 'uses' => '554\AtletasController@create']);
Route::put('atletas/{atletas}', ['as'=> 'atletas.update', 'uses' => '554\AtletasController@update']);
Route::patch('atletas/{atletas}', ['as'=> 'atletas.update', 'uses' => '554\AtletasController@update']);
Route::get('atletas/{id}/delete', array('as' => 'atletas.delete', 'uses' => '554\AtletasController@getDelete'));
Route::get('atletas/{id}/confirm-delete', array('as' => 'atletas.confirm-delete', 'uses' => '554\AtletasController@getModalDelete'));
Route::get('atletas/{atletas}', ['as'=> 'atletas.show', 'uses' => '554\AtletasController@show']);
Route::get('atletas/{atletas}/edit', ['as'=> 'atletas.edit', 'uses' => '554\AtletasController@edit']);

});
